version: '3.3'

services:
  mongo:
    image: mongo:4.0.10
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: python main.py
    restart: on-failure
    depends_on:
      - mongo
