MAT_ECO = ('BQACAgIAAxkBAAIF12Y-UQYgjazfX5osgdW3b1yyAr5FAAIaUAACkkHwSd8OHNiEujf6NQQ')

MAT_EST = 'BQACAgIAAxkBAAIF4WY-UkchpzDzZE9lQKntcVH6onJQAAIiUAACkkHwSUOPPeTFYr8NNQQ'

TEX_MAT = 'BQACAgIAAxkBAAIF42Y-UpJ-Re6Y0eTMVMBFK8qR8FPrAAInUAACkkHwSTbpEK1qbK0vNQQ'

FUND = 'BQACAgIAAxkBAAIF5WY-Uy1MigLhQJNETIrjWUQRO-RxAAItUAACkkHwScnNl1KD3GC3NQQ'

INF = 'BQACAgIAAxkBAAIF52Y-U6JuFTF_dr3L7WH7KHGF17f8AAI1UAACkkHwSUxJrXbqDszsNQQ'